# vim: ft=yaml
---
driver:
  name: docker

provisioner:
  name: salt_solo
  formula: kafka
  state_top:
    base:
      "*":
        - kafka

platforms:
  - name: debian-8

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        kafka.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - kafka
